name: Python CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
    defaults:
      run:
        working-directory: python

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install odin-data python pacakge
        run: |
          python -m pip install --upgrade pip
          pip install .[dev,meta_writer]
          python -c "from odin_data import __version__; print(__version__)"

      - name: Run tests
        run:
          pytest -vs --cov=odin_data --cov-report=term-missing
